[theme]
primaryColor = "#1D428A"
backgroundColor = "#F8FBFF" 
secondaryBackgroundColor = "#C6D2DF"   # White
textColor = "#222028"   # Dark Grey
font = "sans serif"

[client]
showSidebarNavigation = false
