[theme]
primaryColor = "#1D428A"
backgroundColor = "#D6DBDC" 
secondaryBackgroundColor = "#C0C2C6"   # White
textColor = "#222028"   # Dark Grey
font = "sans serif"

[client]
showSidebarNavigation = false
