[theme]
primaryColor = "#1D428A"
backgroundColor = "#F3F4F6" 
secondaryBackgroundColor = "#253C73"   # White
textColor = "#222028"   # Dark Grey
font = "sans serif"

[client]
showSidebarNavigation = false


